Revert "RDKBDEV-344 : Update snmp_subagent status using sysevent API"
This reverts commit c36ace9c1f7d3d4d50b662e65da1ce3847284f39.

Reason for revert: This is causing build failures after meta-rdk-broadband/52104 is merged:

| ../../../../../../../../../rdkb/components/opensource/ccsp/CcspSnmpPa/source/SnmpPlugin/ccsp_snmp_subagent.c: In function 'openCommonSyseventConnection':
| ../../../../../../../../../rdkb/components/opensource/ccsp/CcspSnmpPa/source/SnmpPlugin/ccsp_snmp_subagent.c:69:28: error: implicit declaration of function 's_sysevent_connect' [-Werror=implicit-function-declaration]
|          commonSyseventFd = s_sysevent_connect(&commonSyseventToken);
|                             ^~~~~~~~~~~~~~~~~~
| cc1: all warnings being treated as errors
| Makefile:620: recipe for target 'snmp_subagent-ccsp_snmp_subagent.o' failed
| make[3]: *** [snmp_subagent-ccsp_snmp_subagent.o] Error 1

Change-Id: Ib1ae6c6585cd7fa596726bfc5ad3b620598b92a8